[project]
name = "dashboard_seromo"
version = "0.1.0"
description = "Loja Seromo"
authors = ["Felipe , Gabriel <fkauhe12@gmail.com>"]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.9.2",
    "numpy>=2.1.2",
    "pandas>=2.2.3",
    "streamlit>=1.39.0",
]